name: BA_HT_Env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - numpy=1.21.5
  - pandas=1.4.4
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - tensorflow=2.10.1
  - keras=2.10.0
  - jupyter
  - ipython
  - pip
  - pip:
      - visualkeras
      - keras-tuner
      - kaggle